### PR TITLE
Database and Table file adjustments

### PR DESCRIPTION
**Pull request by Brlan7**
- Added additional documentation to database file to better understand the code.
- Deleted the testing area in database file as is not needed since we can test in GUI now
- Adjusted the Read button in Table file so that it calls the database class. As well as added extra documentation. 
- Adjusted the Connect button in Table file so that it also imports the csv file by calling the importing method in database class.

### CODE REVIEW

**Review by SHamil36 — APPROVED** [review]
Looks good overall with some QA changes and the documentation definitely helps. This should be the last pull request of this sprint.

**Comment by FindingDorri** [comment]
Everything looks good. Let's merge it.

**Comment by FindingDorri** [comment]
Everything looks good. Let's merge it.

**Comment by FindingDorri** [comment]
Everything looks good. Let's merge it.

**Review by FindingDorri — COMMENTED** [review]
Everything looks good. Let's merge it.

**Review by FindingDorri — APPROVED** [review]

**Pull request merged**
